# -*- coding: utf-8 -*-
"""DAY1-practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4p07iBX-i-J8ruepQGpcfppAdB8ycpW
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_data_explorer_dataset.csv")

electronics_students = len(df[df['department'] == 'Electronics'])
print("Electronics Students :", electronics_students)

female_attendance = df[df['gender'] == 'Female']['attendance_percentage'].mean()
print("Average Female Attendance :", female_attendance)

low_programming = df[df['programming_score'] == df['programming_score'].min()]
display(low_programming[['name', 'programming_score']])

math_above_80 = len(df[df['math_score'] > 80])
print("Students Above 80 in Math :", math_above_80)

avg_total = df[df['attendance_percentage'] > 90]['total_score'].mean()
print("Average Total Score :", avg_total)