# -*- coding: utf-8 -*-
"""DAY1-class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWuWgfkPQSWA0rJNFGwkr1fPWac3zJsY
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('student_performance.csv')
print(df.head())

df.head()

df.tail()

df.shape

"""30 rows and 13 columns

"""

df.shape[0]

"""rows"""

df.shape[1]

"""columns


"""

print(df.columns.tolist())

print(df.index.tolist())

"""Returns the datatype of every column.

It checks each column and tells what type of data is stored
"""

df.dtypes

"""describe() is used to get the statistical summary of numerical columns in a DataFrame.

It quickly shows:

count,
mean,
minimum value,
maximum value,
standard deviation,
percentiles,
"""

df.describe()

import pandas as pd

df = pd.read_csv("student_performance.csv")

df.loc[0:4, 'semester'] = None

display(df.head())

display(df['semester'].isnull().sum())

df['semester'] = df['semester'].fillna(5)

display(df.head())

df['department'].unique()

cs_students = df[df['department'] == 'Civil']

display(cs_students)

for dept in df['department'].unique():

    print("\nDepartment:", dept)

    dept_data = df[df['department'] == dept]

    male_count = dept_data[dept_data['gender'] == 'Male'].shape[0]
    female_count = dept_data[dept_data['gender'] == 'Female'].shape[0]

    print("Male Count:", male_count)
    print("Female Count:", female_count)

cs_students = df[df['department'] == 'Computer Science']

display(cs_students[['name', 'attendance_percentage']])

ch_students = df[(df['city'] == 'Chennai') |(df['city']=='Mumbai')]

display(ch_students[['name','department','programming_score']])

low_attendance = df[df['attendance_percentage'] <= 75]

display(low_attendance[['name', 'department', 'attendance_percentage']])

print("Total Students:", len(low_attendance))

min_index = df['programming_score'].idxmin()

display(df.loc[min_index, ['name', 'department', 'programming_score']])

df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
top_students=df.loc[df['total_score'].idxmin()]


print(top_students[['name', 'department', 'total_score']])