# -*- coding: utf-8 -*-
"""DAY1-MINIPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOhdK_SN84lPsO5qAIMNG8fVGGOqngsX
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

print("=" * 50)
print("     STUDENT PERFORMANCE EXPLORER")
print("=" * 50)

import pandas as pd

df = pd.read_csv("student_data_explorer_dataset.csv")

print("Total Students :", df.shape[0])

print("Total Columns :", df.shape[1])

print("Unique Departments :", df['department'].nunique())

dept_count = df['department'].value_counts()

display(dept_count)

print("Highest Math Score :", df['math_score'].max())

print("Lowest Math Score :", df['math_score'].min())

print("Average Math Score :", df['math_score'].mean())

print("Average Programming Score :", df['programming_score'].mean())

print("Average Attendance :", df['attendance_percentage'].mean())

gender_avg = df.groupby('gender')['total_score'].mean()

display(gender_avg)

top_students = df.sort_values(by='total_score', ascending=False).head(5)

display(top_students[['name', 'department', 'total_score']])

low_attendance = df[df['attendance_percentage'] < 75]

display(low_attendance[['name', 'department', 'attendance_percentage']])

if len(low_attendance) > 0:

    display(low_attendance[['name', 'department', 'attendance_percentage']])

else:

    print("All students have attendance above 75%")