# -*- coding: utf-8 -*-
"""DAY6:PromptEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3ZLkMwbw0SZJrIRRnOitB0tKwPezv-i
"""

!pip install langchain langchain-groq langchain-community langchain-core --quiet

#template code to build the AI agents -zero shot prompting example

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]=""

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser

response=chain.invoke({
    "instruction" : "Translate 'Good evening, how are you?' to Tamil"})
print(response)

#template code to build the AI agents -zero shot prompting example

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]=""

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="""Follow the instruction and provide the output clearly:\n\nInstruction:{instruction}\n\nAnswer:"""
)
parser=StrOutputParser()
chain = prompt | llm | parser

response=chain.invoke({
    "instruction" : "Teach me the basics of java ?"})
print(response)

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]=""

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt = PromptTemplate(
    input_variables=["question"],
    template="""

You are an advanced reasoning assistant.


Step 1: Generate THREE different reasoning paths to solve the problem.
Step 2: Evaluate each path for correctness.
Step 3: Choose the best path.
Step 4: Provide the final answer.


Question: {question}


Return the answer in this format:
Reasoning Path 1:
Reasoning Path 2:
Reasoning Path 3:
Evaluation:
Best Path:
Final Answer:
"""
)
parser=StrOutputParser()
chain = prompt | llm | parser

response=chain.invoke({
    "question" : "Teach me the basics of java ?"})
print(response)

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"] = ""

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

prompt = PromptTemplate(
    input_variables=["problem"],
    template="""
You are an expert Data Structures and Algorithms tutor.

Given the LeetCode problem below:

Problem:
{problem}

Perform the following:

1. Generate FOUR different approaches.
2. Provide Java code for each approach.
3. Mention Time Complexity.
4. Mention Space Complexity.
5. Compare all approaches.
6. Select the most optimized solution.
7. Explain why it is optimal.

Return the result in this format:

Approach 1:
Code:
Time Complexity:
Space Complexity:

Approach 2:
Code:
Time Complexity:
Space Complexity:

Approach 3:
Code:
Time Complexity:
Space Complexity:

Approach 4:
Code:
Time Complexity:
Space Complexity:

Comparison Table:

Best Solution:

Optimized Java Code:

Explanation:
"""
)

parser = StrOutputParser()

chain = prompt | llm | parser

response = chain.invoke({
    "problem": "Two Sum"
})

print(response)

pip install twilio

#Twilio Sandbox
import os
from getpass import getpass    # to ensure that the data is not leak
from twilio.rest import Client

# --- Twilio credentials ---
TW_SID = os.environ.get('TWILIO_SID')
TW_TOKEN = os.environ.get('TWILIO_TOKEN')


if not TW_SID or not TW_TOKEN:
    print("Enter your Twilio Account SID and Auth Token:")
    TW_SID = getpass("Twilio SID: ")
    TW_TOKEN = getpass("Twilio Token: ")
    os.environ['TWILIO_SID'] = TW_SID
    os.environ['TWILIO_TOKEN'] = TW_TOKEN
#twilio whatsapp sandbox sender
FROM = 'whatsapp:+14155238886'

TO = input("Enter your WhatsApp number (e.g.. +91XXXXXXXXXX): ").strip()

if not TO.startswith('whatsapp'):
  TO = f'whatsapp:{TO}'

#inititalize twilio client
client = Client(TW_SID, TW_TOKEN)

msg=client.messages.create(
    body='Hello from Twilio whatsApp Sandbox - test message!',
    from_=FROM,
    to=TO
)

print(' Message send successfully')
print('Message STD:',msg.sid)

