# -*- coding: utf-8 -*-
"""DAY3-class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVs7pqhDFJiuMKYvsdQl2JFHi5GqXgv0
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import requests
import json
import matplotlib.pyplot as plt
import matplotlib

import matplotlib.patches as mpatches
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("Libraries imported successfully,")
print(f"   pandas version     : {pd.__version__}")
print(f"   requests version   : {requests.__version__}")
print(f"   Loadedat           : {datetime.now().strftime('%Y -%m-%d %H:%M:%S')}")
print(f"   json version       : {json.__version__}")
print(f"   matplotlib version : {matplotlib.__version__}")

raw_df=pd.read_csv('messy_sales_data.csv')
print(f"Rows    :{raw_df.shape[0]}")
print(f"Columns :{raw_df.shape[1]}")
print(f"Column name : {raw_df.columns.tolist()}")
print(f"Rows numbers: {raw_df.index.tolist()}")
print("\n                                             First 5 rows")
raw_df.head()

print("=" * 55)
print("          DATA QUALITY DIAGNOSIS REPORT  ")
print("=" * 55)


print("\n[1] MISSING VALUES per column: ")
print(raw_df.isnull().sum())

print(f"\n[2] DUPLICATE ROWS: {raw_df.duplicated().sum()}")


print(f"\n[3] DATA TYPES")
print(raw_df.dtypes)

print("\n[4] UNIQUE CATEGORIES:", raw_df['category'].dropna().unique().tolist())
print("[4] SAMPLE ORDER DATES:", raw_df['order_date'].unique().tolist())
print("[4] SAMPLE NAMES:", raw_df['customer_name'].dropna().unique()[:8].tolist())

print("\n[1] MISSING VALUES per column: ")
print(raw_df.isnull().sum())

#create a working copy (ETL best practices)

df=raw_df.copy()
print(f"Working copy created successfully: {df.shape}")

print(df.isnull().sum())

from numpy import median
#Handling the missing values

print(f"Total missing vlaues BEFORE fix: {df.isnull().sum().sum()}")

df['customer_name'].fillna('Unknown Customer', inplace=True)  #diirect ha df leyy poi replace panna porom


median_qty=df['quantity'].median()
df['quantity'].fillna(median_qty, inplace=True)
print(f"  Filled missing quantity with medican value: {median_qty}")

df['category'].fillna('Uncategorized', inplace=True)

df['product'].fillna('Unknown Product', inplace=True)

print(f"Total missing vlaues AFTER fix: {df.isnull().sum().sum()}")

print(f"Duplicate value {df.duplicated().sum()}")

#for duplication recheck
print(f"Rows BEFORE duplication: {len(df)}")
print(f"Duplicate rows found   : {df.duplicated().sum()}")

duplicate_mask=df.duplicated(keep='first')
print("\nThe duplicate rows (all copies shown):")
print(df[duplicate_mask][['order_id','customer_name','product','order_date']].to_string(index=True))

df.drop_duplicates(inplace=True)   #duplicate to true
df.reset_index(drop=True, inplace=True)    #for specific duplicate index
print(f"\nRows AFTER duplication  : {len(df)}")
print(f"Rows removed              : {len(raw_df)-len(df)}")

#pare mixed date formats to single pattern


print("Sample dat BEFORE parsing:")
print(df['order_date'].head(10).tolist())

#pd.to_datetime ---convert text date into the proper datetime object
#errors='coerce'---update specifi date to the NaT
df['order_date']=pd.to_datetime(df['order_date'], dayfirst=False, errors='coerce') #day meant for dates

nat_mask=df['order_date'].isnull()
 #True  -> invalid date
#False -> valid date

df.loc[nat_mask, 'order_date']=pd.to_datetime(raw_df.loc[nat_mask, 'order_date'], dayfirst=True, errors='coerce')

nat_count=df['order_date'].isnull().sum()
print(f"\nUnprarseable dates remaining (NaT): {nat_count}")

df['year']       =df['order_date'].dt.year
df['month']     =df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['day_name']  =df['order_date'].dt.strftime('%A')

print("\nSample dates AFTER parsing:")
print(df['order_date'].head(10).tolist())

print("sample dates before parsing")
print(df['order_date'].dt.strftime('%Y-%m-%d').head(10).tolist())
df['order_date']=pd.to_datetime(df['order_date'],dayfirst=False,errors='coerce')
nat_mask=df['order_date'].isnull()
df.loc[nat_mask,'order_date']=pd.to_datetime(raw_df.loc[nat_mask,'order_date'],dayfirst=True,errors='coerce')
nat_count=df['order_date'].isnull().sum()
print("unparsable dates remaining ",nat_count)
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['day_name']=df['order_date'].dt.strftime('%A')
print("sample dates after parsing")
print(df[['year','month','month_name','day_name']].head(10))

#standardize customer names

print("Names BEFORE standardization (smaple):")
print(df['customer_name'].unique()[:8].tolist())

df['customer_name']=df['customer_name'].str.strip().str.title()

print("\nNames AFTER standardization (sample):")
print(df['customer_name'].unique()[:8].tolist())

wrong_mask=(df['product']=='Keyboard') & (df['category'] == 'Electronics')

print(f"Rows to fix: {wrong_mask.sum()}")
print("Before fix:")
print(df[wrong_mask][['order_id','product','category']].to_string(index=False))

df.loc[wrong_mask, 'category'] = 'Accessories'


print("\nAfter fix:")
print(df[wrong_mask][['order_id', 'product', 'category']].to_string(index=False))
print(sorted(df['category'].unique().tolist()))

print(df.columns.tolist())



df['quantity']=pd.to_numeric(df['quantity'], errors='coerce').astype(int)
df['unit_price']=pd.to_numeric(df['unit_price'], errors='coerce')
df['revenue']=df['quantity']*df['unit_price']

print("Revenue column created successfully")
print("\nSample: quantity X unit_price = revenue ")
print(df[['customer_name','product','quantity','unit_price','revenue']].head(8).to_string(index=False))

# ============================================================
# CELL 11 — Post-Cleaning Validation Report
# ============================================================


# Calculate the data quality score
# We check 5 things: no missing values, no duplicates, no date nulls, no revenue nulls
# Each passing check contributes 20 points (5 checks × 20 = 100)
missing_count   = df.isnull().sum().sum()
duplicate_count = df.duplicated().sum()
date_nulls      = df['order_date'].isnull().sum()
revenue_nulls   = df['revenue'].isnull().sum()


checks_passed   = sum([
    missing_count   == 0,   # 20 points
    duplicate_count == 0,   # 20 points
    date_nulls      == 0,   # 20 points
    revenue_nulls   == 0,   # 20 points
    len(df)         > 0     # 20 points (dataset is not empty)
])
quality_score = checks_passed * 20


# ── Print the report ─────────────────────────────────────────
print("=" * 55)
print("  POST-CLEANING VALIDATION REPORT")
print("=" * 55)
print(f"  Original rows   : {len(raw_df)}")
print(f"  Cleaned rows    : {len(df)}")
print(f"  Rows removed    : {len(raw_df) - len(df)} (duplicates)")
print(f"  Missing values  : {missing_count}")
print(f"  Duplicates      : {duplicate_count}")
print(f"  Date nulls      : {date_nulls}")
print(f"  Revenue nulls   : {revenue_nulls}")
print(f"  Columns total   : {len(df.columns)}")
print("=" * 55)
print(f"  DATA QUALITY SCORE : {quality_score}/100")
print(f"  DATA IS CLEAN      : {quality_score == 100}")
print("=" * 55)


# ── Actionable Debugging Suggestions ─────────────────────────
if missing_count > 0:
    print("\n  ACTION REQUIRED: Missing values detected.")
    print("  → Use df['column'].fillna(value, inplace=True)")
    print("  → For numbers: fillna(df['column'].median())")
    print("  → For text   : fillna('Unknown')")


if duplicate_count > 0:
    print("\n  ACTION REQUIRED: Duplicate rows detected.")
    print("  → Use df.drop_duplicates(inplace=True)")


if date_nulls > 0:
    print("\n  ACTION REQUIRED: Unparseable dates found.")
    print("  → Check for unusual date formats in the raw data")
    print("  → Use pd.to_datetime(col, dayfirst=True, errors='coerce')")


if quality_score == 100:
    print("\n  All checks passed. Data is ready for analysis.")

output_filename='clean_sales_Data.csv'
df.to_csv(output_filename, index=False)

print(f"Cleaned data saved to: {output_filename}")
print(f"Final dataset: {df.shape[0]} rows X {df.shape[1]} columns")

SERP_API_KEY='fea6ced7b2086c4e70e031cb66b4bb6861883645d1b8e1531dde1ecc6a14ca32'
SERP_URL='https://serpapi.com/search.json'
SEARCH_QUERY='Data Engineer India'

print(f"SerpAPI Key  : {'Set (live data)' if SERP_API_KEY != 'YOUR_SERPAPI_KEY_HERE' else 'Not set (fallback data will be used)'}")
print(f"Search query :{SEARCH_QUERY}")

# ============================================================
# CELL 22 — EXTRACT: Fetch Job Listings from SerpAPI
# ============================================================


def fetch_jobs(query, api_key, num_pages=2):
    """
    Fetches job listings from Google Jobs via SerpAPI.


    Parameters:
        query    (str) : The job search query (e.g. 'Data Engineer India')
        api_key  (str) : Your SerpAPI key
        num_pages(int) : Number of result pages to fetch (default: 2)


    Returns:
        list : A list of job dictionaries
    """
    all_jobs = []


    for page in range(num_pages):
        # API pagination: 'start' tells the API which result to start from
        # Page 0: results 0-9, Page 1: results 10-19, etc.
        params = {
            'engine'    : 'google_jobs',  # Use the Google Jobs search engine
            'q'         : query,
            'api_key'   : api_key,
            'hl'        : 'en',           # Language: English
            'start'     : page * 10       # Pagination offset
        }


        try:
            response = requests.get(SERP_URL, params=params, timeout=15)


            if response.status_code == 200:
                data = response.json()


                # 'jobs_results' is the key in the JSON that holds the job listings
                jobs = data.get('jobs_results', [])


                for job in jobs:
                    # Extract and normalize each job's fields
                    # .get('key', 'default') returns the value if the key exists,
                    # or 'default' if it does not — prevents KeyError crashes
                    all_jobs.append({
                        'title'      : job.get('title', 'Unknown Title'),
                        'company'    : job.get('company_name', 'Unknown Company'),
                        'location'   : job.get('location', 'Unknown Location'),
                        'posted'     : job.get('detected_extensions', {}).get('posted_at', 'Unknown'),
                        'salary'     : job.get('detected_extensions', {}).get('salary', 'Not Disclosed'),
                        'job_type'   : job.get('detected_extensions', {}).get('schedule_type', 'Not Specified'),
                        'description': job.get('description', '')[:300]  # First 300 characters only
                    })


                print(f"  Page {page + 1}: fetched {len(jobs)} jobs")
            else:
                print(f"  Page {page + 1}: API error {response.status_code}")


        except Exception as e:
            print(f"  Page {page + 1}: error — {e}")


    return all_jobs


# ── Actually call the function ────────────────────────────────
job_records = []


if SERP_API_KEY != 'YOUR_SERPAPI_KEY_HERE':
    print(f"Fetching job listings for: '{SEARCH_QUERY}'")
    job_records = fetch_jobs(SEARCH_QUERY, SERP_API_KEY)
    print(f"Total jobs fetched: {len(job_records)}")
else:
    print("No SerpAPI key provided — fallback job data will be loaded next.")

import pandas as pd
from google.colab import files

jobs_df = pd.DataFrame(job_records)
jobs_output_filename = 'fetched_job_listings.csv'

jobs_df.to_csv(jobs_output_filename, index=False)

print(f"Job listings saved to: {jobs_output_filename}")

files.download(jobs_output_filename)

