# -*- coding: utf-8 -*-
"""DAY3-miniproject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8U86JAE66E2-FAatg2nHIczjP3atwgK

## Weather Data ETL Project
"""

#Extract Data from API
import requests
import pandas as pd

API_KEY = 'YOUR_API_KEY'

base_url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "q": "London,UK",
    "appid": API_KEY,
    "units": "metric"
}

response = requests.get(base_url, params=params)
data = response.json()

# Check if the API call was successful
if data.get('cod') == 200: # 'cod' is typically 200 for a successful response
    print(f"Weather data for London, UK:")
    display(data)
else:
    print(f"Error fetching weather data: {data.get('message', 'Unknown error')}")
    print("Please check your API key and try again. Refer to https://openweathermap.org/faq#error401")
    data = None

#Transform JSON Data
if data: # Only proceed if data is not None (i.e., API call was successful)
    weather_data = {
        "City": data["name"],
        "Temperature": data["main"]["temp"],
        "Humidity": data["main"]["humidity"],
        "Pressure": data["main"]["pressure"],
        "Weather": data["weather"][0]["description"],
        "Wind Speed": data["wind"]["speed"]
    }

    df = pd.DataFrame([weather_data])

    display(df)
else:
    print("Cannot process weather data because the API call failed in the previous step.")

#Load Data into CSV
df.to_csv("weather_data.csv", index=False)

print("Data saved successfully!")
