# -*- coding: utf-8 -*-
"""DAY3-MiniProject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiTUjUXL0Hx01V_wIQybEdsM3EPOneC5
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd

df = pd.read_excel("Employee_datas.xlsx")

print("="*100)
print("                                  ORIGINAL DATASET")
print("="*100)
display(df)
print("\nRows:", len(df))

before = len(df)

df.drop_duplicates(inplace=True)

after = len(df)

print("AFTER REMOVING DUPLICATES")

display(df)

print(f"\nRows Before: {before}")
print(f"Rows After : {after}")
print(f"Duplicates Removed: {before-after}")

print("\n")
print("="*50)
print("ROWS WITH MISSING VALUES")
print("="*50)

print(df[df["Age"].isnull()])

before = len(df)

df.dropna(subset=["Age"], inplace=True)

after = len(df)

print("\nAFTER REMOVING MISSING AGE")
print(df)

print(f"\nRows Before: {before}")
print(f"Rows After : {after}")

print("\n")
print("="*50)
print("SALARY BEFORE CONVERSION")
print("="*50)

print(df["Salary"].head())

print("\n")
print("="*50)
print("INVALID SALARIES")
print("="*50)

df["Salary"] = df["Salary"].astype(str).str.replace(",", "").astype(float)
display(df[df["Salary"] < 0])

before = len(df)

df = df[df["Salary"] > 0]

after = len(df)

print("\nAFTER REMOVING INVALID SALARIES")
display(df)

print(f"\nRows Before: {before}")
print(f"Rows After : {after}")

#Calculate yearly salary
#Before

print("BEFORE ADDING YEARLY SALARY")
display(df[["First Name","Salary"]].head())

#Create
df["Yearly Salary"] = df["Salary"] * 12

#After
print("AFTER ADDING YEARLY SALARY")
display(df[["First Name","Salary","Yearly Salary"]].head())

#load
df.to_csv("cleaned_employee_salary.csv", index=False)

print("\n")
print("="*50)
print("FINAL CLEANED DATASET")
print("="*50)

display(df)

print("\nTotal Records:", len(df))
print("\nDataset saved as cleaned_employee_salary.csv")