# -*- coding: utf-8 -*-
"""DAY4-class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pukyzWk9ss9za1qCqDapI0__VNcJJrHP
"""

!pip install pyspark --quiet
print('PySpark installation complete!')

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.functions import year, month, to_date, col, round as spark_round

import matplotlib.pyplot as plt
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

spark = SparkSession.builder \
    .appName("Day4_BigData_Sales") \
    .config("spark.sql.adaptive.enabled", "true") \
    .getOrCreate()

print(f"Spark Version : {spark.version}")
print("SparkSession : ACTIVE")

from google.colab import files
uploaded=files.upload()

#ETL la E
#inferschema : find the datatypes of fields inside the table
#printSchema : root directory la columns ha mattum show pannum

df_bronze = spark.read \
    .option('header','true') \
    .option('inferSchema','true') \
    .csv('large_sales_data.csv')

print('===BRONZE LAYER ---Row Data ===')
print(f'Rows  : {df_bronze.count()}')

print(f'Columns : {len(df_bronze.columns)}')
print(f'Names : {df_bronze.columns}')
print()
df_bronze.printSchema()

print('First 5 rows:')
df_bronze.show(5, truncate=False)

print('\nBasic statistics for numeric columns:')
df_bronze.select('quantity','unit_price','revenue').describe().show()

df_bronze.write \
    .mode('overwrite') \
    .parquet('sales_bronze.parquet')

print('Bronze parquet saved: sales_bronze.parquet')

#compare file sizes
import os

def get_dir_size(path):
  """ Get total size of a file or directory in KB."""
  if os.path.isfile(path):
    return os.path.getsize(path)/1024
  total=0
  for dirpath, dirname, filename in os.walk(path):
    for f in filename:
      total += os.path.getsize(os.path.join(dirpath, f))
    return total/1024

csv_size= get_dir_size('large_sales_data.csv')
parquet_size=get_dir_size('sales_bronze.parquet')
reduction =(1-parquet_size/csv_size)*100

print(f'\nCSV size : {csv_size:.1f}KB')
print(f'Parquet size : {parquet_size:.1f}KB')
print(f'Reduction : {reduction:.1f}% smaller')
print(f'\nAt 1 TB scale: CSV=1000 GB -> Parquet= {1000*(1-reduction/100):.0f}GB')

df_silver=df_bronze \
    .dropDuplicates() \
    .dropna(subset=['order_id','product','revenue'])

df_silver=df_silver.withColumn(
    'order_date',
    to_date(col('order_date'),'dd-MM-yyyy')
)

df_silver=df_silver \
    .withColumn('year',year('order_date')) \
    .withColumn('month',month('order_date'))

df_silver=df_silver.withColumn(
    'revenue_category',
    F.when(col('revenue')>40000,'High')
    .when(col('revenue')<10000,'Medium')
    .otherwise('low')
)

print(f'Silver layer rows: {df_silver.count()}')
print(f'New columns added : year, month, revenue_category')
df_silver.select('product', 'revenue', 'year', 'month', 'revenue_category').show(5, truncate=False)
print(f'Silver layer columns: {len(df_silver.columns)}')
print(f'Silver layer names: {df_silver.columns}')

#silver layer as the parquet
df_silver.write \
    .mode('overwrite') \
    .parquet('sales_silver.parquet')

print('Silver Parquet saved: sales_silver.parquet')
print(f'Silver size: {get_dir_size("sales_silver.parquet"):.1f}KB')

df_verify=spark.read.parquet('sales_silver.parquet')
print('\n=== Verify Silver layer ===')
print(f'Read- back rows: {df_verify.count()} (should match silver count)')
df_verify.printSchema()

#query 1 = top 5 product by total revenue and transform

top_products = df_silver \
    .groupBy('product') \
    .agg(
        F.sum('revenue').alias('total_revenue'),
        F.count('order_id').alias('num_orders'),
        F.avg('revenue').alias('avg_order_revenue')
    ) \
    .orderBy('total_revenue', ascending=False) \
    .limit(5)

print('==== Top 5 products by Revenue ====')
top_products.show(truncate=False)

print(f'Names : {df_silver.columns}')

#query -2 : revenue by region

region_revenue=df_silver \
    .groupBy('region') \
    .agg(
        F.sum('revenue').alias('total_revenue'),
        F.count('order_id').alias('total_orders'),
        F.count_distinct('customer_name').alias('unique_customers')
    ) \
    .orderBy('total_revenue', ascending=False)

print('==== Revenue by Region ====')
region_revenue.show(truncate=False)

print('\n==== Unique customer names in West region ====')
west_customer_names = df_silver.filter(F.col('region') == 'West').select('customer_name').distinct()
west_customer_names.show(truncate=False)

#query -3 montly revenue

monthly_revenue_orders = df_silver \
    .groupBy(F.col('year'), F.col('month')) \
    .agg(
        F.sum('revenue').alias('monthly_revenue'),
        F.count('order_id').alias('monthly_orders')
    ) \
    .orderBy(F.col('year'), F.col('month')) \
    .withColumn('month_name', F.date_format(F.to_date(F.concat(F.col('year'), F.lit('-'), F.lpad(F.col('month'), 2, '0'), F.lit('-01')), 'yyyy-MM-dd'), 'MMMM'))

print('==== Monthly Revenue and Orders ====')
monthly_revenue_orders.select('month', 'month_name', 'monthly_revenue', 'monthly_orders').show(truncate=False)

GOLDEN LAYER :
#parquet pyspark to convert to the dataframe
#coding ha snowflake use panni visualize pannalam

gold_region = region_revenue
gold_region.write.mode('overwrite').parquet('gold_region_revenue.parquet')
print('Gold 1 saved: gold_region_revenue.parquet')

#Gold table 2 : product performance summary

gold_products = df_silver \
    .groupBy('product','category') \
    .agg(
        F.sum('revenue').alias('total_revenue'),
        F.count('order_id').alias('units_sold'),
        spark_round(F.avg('quantity'),1).alias('avg_quantity_per_order'),
        F.max('revenue').alias('largest_order')
    ) \
    .orderBy('total_revenue', ascending=False)

gold_products.write.mode('overwrite').parquet('gold_product_performance.parquet')
print('Gold 2 saved: gold_product_sumary.parquet')

#convert gold tables to pandas for visualization

region_pd =spark.read.parquet('gold_region_revenue.parquet').toPandas()
product_pd = spark.read.parquet('gold_product_performance.parquet').toPandas()
monthly_pd=spark.read.parquet('monthly_revenue_orders.parquet').toPandas()

print('Gold tables converted to Pandas')
print(f'Region: {region_pd.shape}')
print(f'Product: {product_pd.shape}')
print(f'Monthly: {monthly_pd.shape}')



region_pd=region_pd.sort_values(by='total_revenue', ascending=False)
product_pd=product_pd.sort_values(by='total_revenue', ascending=False)
monthly_pd=monthly_pd.sort_values(by='monthly_revenue', ascending=False)

display(region_pd.head())
display(product_pd.head())
display(monthly_pd.head())

#

fig, axes = plt.subplots(1,1, figsize=(18, 13))
fig.suptitle(
    'Big Data Sales Dashboard - PySpark medallion Pipeline\n'
    '5,000 orders | processed with apache spark',
    fontsize=18, fontweight='bold',color='Black',y=1.01
)
colors4=['Red','Blue','Yellow','Green','pink']

ax1=axes.twinx()
bars1=ax1.bar(region_pd['region'],region_pd['total_revenue'],color=colors4[:len(region_pd)],edgecolor='white')

for bar in bars1:
  ax1.text(bar.get_x()+bar.get_width()/2,bar.get_height()*1.01,
           f'{bar.get_height()/1e6:.1f}M',
           ha='center',fontweight='bold',color='Black',fontsize=10)
#sidela irukurathu tha tik values nu solluvanga
ax1.set_title('Total Revenue by Region',fontsize=14, fontweight='bold')
ax1.set_ylabel('Revenue',fontsize=14)
ax1.set_xlabel('Region',fontsize=14)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: f'{x/1e6:.1f}M'))

ax1.grid(axis='x', linestyle=':', alpha=0.8)
ax1.grid(axis='y', linestyle=':', alpha=0.8)

ax1.legend(title="Metrics",frameon=False)

#panel 1
fig, axes = plt.subplots(1,2, figsize=(18, 13))
fig.suptitle(
    'Big Data Sales Dashboard - PySpark medallion Pipeline\n'
    '5,000 orders | processed with apache spark',
    fontsize=18, fontweight='bold',color='Black',y=1.01
)
colors4=['Red','Blue','Yellow','Green','pink']

#panel 1

ax1=axes[0]
bars1=ax1.bar(region_pd['region'],region_pd['total_revenue'],color=colors4[:len(region_pd)],edgecolor='white')

for bar in bars1:
  ax1.text(bar.get_x()+bar.get_width()/2,bar.get_height()*1.01,
           f'{bar.get_height()/1e6:.1f}M',
           ha='center',fontweight='bold',color='Black',fontsize=10)
#sidela irukurathu tha tik values nu solluvanga
ax1.set_title('Total Revenue by Region',fontsize=14, fontweight='bold')
ax1.set_ylabel('Revenue',fontsize=14)
ax1.set_xlabel('Region',fontsize=14)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, loc: f'{x/1e6:.1f}M'))

ax1.grid(axis='x', linestyle=':', alpha=0.8)
ax1.grid(axis='y', linestyle=':', alpha=0.8)

ax1.legend(title="Metrics",frameon=False)

#panel 2
ax2 = axes[1]

bars2 = ax2.barh(region_pd['region'],region_pd['total_revenue'],color=colors4[:len(region_pd)],edgecolor='white',label='Revenue'
)

for bar in bars2:
    ax2.text(bar.get_width()*1.01,
bar.get_y()+bar.get_height()/2,
        f'{bar.get_width()/1e6:.1f}M',
        va='center',
        fontweight='bold'
    )

ax2.set_title('Total Revenue by Region')
ax2.set_xlabel('Revenue')
ax2.set_ylabel('Region')

ax2.xaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, loc: f'{x/1e6:.1f}M'
    )
)

ax2.grid(True, linestyle=':', alpha=0.8)
ax2.legend(title='Metrics', frameon=False)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(8, 8))

colors = ['red', 'blue', 'yellow', 'green', 'pink']

ax.pie(
    region_pd['total_revenue'],
    labels=region_pd['region'],
    colors=colors[:len(region_pd)],
    autopct='%1.1f%%',
    startangle=90,
    shadow=True
)

ax.set_title(
    'Revenue Distribution by Region',
    fontsize=14,
    fontweight='bold'
)

ax.axis('equal')

plt.show()

fig,axes=plt.subplots(2,2,figsize=(18,13))
fig.suptitle(
    'Big Data Sales Dhashboard-PySaprk Medallion Architechture\n'
    '5000 Orders | Procesed with Apache Spark',
    fontsize=18,fontweight='bold',color='#1E2761',y=1.01
)
colors4=['red','blue','yellow','green','pink']
ax1=axes[0,0]
bars1=ax1.bar(region_pd['region'],region_pd['total_revenue'],color=colors4[:len(region_pd)],edgecolor='white')
for bar in bars1:
    ax1.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * 1.01,f"${bar.get_height() / 1e6:.1f}M",
        ha='center',fontsize=10,fontweight='bold',color='brown')

ax1.set_title('TOTAL REVENUE BY REGION',fontsize=14,fontweight='bold')
ax1.set_ylabel('REVENUE',fontweight='bold',fontsize=14)
ax1.set_xlabel('REGION',fontweight='bold',fontsize=14)
ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'${x/1e6:.1f}M'))
ax1.grid(axis='y',alpha=0.3,linestyle='--')



ax2 = axes[0,1]
bars2 = ax2.barh(product_pd['product'],product_pd['total_revenue'],color=colors4[:len(region_pd)],edgecolor='white')

for bar in bars2:
    ax2.text( bar.get_width() * 1.01,bar.get_y() + bar.get_height()/2,f"${bar.get_width()/1e6:.1f}M",
        va='center',fontsize=10,fontweight='bold',color='darkblue')


ax2.set_title('TOTAL REVENUE BY TOP PRODUCTS',fontsize=10,fontweight='bold')
ax2.set_xlabel('REVENUE',fontweight='bold',fontsize=10)
ax2.set_ylabel('PRODUCT',fontweight='bold',fontsize=10)
ax2.xaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'${x/1e6:.1f}M'))



ax3=axes[1,0]
pie=ax3.pie(region_pd['total_revenue'],labels=region_pd['region'],autopct='%1.1f%%',colors=colors4[:len(region_pd)])

ax3.set_title('REVENUE SHARE BY REGION',fontsize=14,fontweight='bold')

ax4=axes[1,1]
month_names=['January','February','March','April','May','June','July','August','September','October','November','December']
monthly_labels=[month_names[i-1] for i in monthly_pd['month']]
ax4.plot(monthly_labels,monthly_pd['monthly_revenue'],marker='o',linewidth=2.5,color='blue',markersize=8,markerfacecolor='white',markeredgewidth=2)
ax4.fill_between(range(len(monthly_pd)),monthly_pd['monthly_revenue'],color='lightblue',alpha=0.15)
ax4.set_title('MONTHLY REVENUE TREND',fontsize=14,fontweight='bold')
ax4.set_xlabel('MONTH',fontsize=14,fontweight='bold')
ax4.set_ylabel('REVENUE',fontsize=14,fontweight='bold')
ax4.yaxis.set_major_formatter(plt.FuncFormatter(lambda x,_: f'${x/1e6:.1f}M'))
ax4.grid(alpha=0.3,linestyle='--')
ax4.tick_params(axis='x',rotation=30,labelsize=9)