# -*- coding: utf-8 -*-
"""DAY2-mini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUVmpEbm_KvUadex08OSg_xFZxnW8mmO
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_performance.csv")

import sqlite3

conn = sqlite3.connect("student.db")

df.to_sql(
    'student_performance',
    conn,
    if_exists='replace',
    index=False
)

query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = pd.read_sql_query(query, conn)

display(tables)

import sqlite3

conn = sqlite3.connect("student_performance.db")

import sqlite3

# Reconnect database
conn = sqlite3.connect("student_performance.db")

query1 = """
    SELECT department,
           ROUND(AVG(math_score),2) AS avg_math
    FROM student_performance
    GROUP BY department
    ORDER BY avg_math DESC
"""

panel1 = pd.read_sql_query(query1, conn)

display(panel1)

query2 = """
    SELECT department,
           COUNT(*) AS total_students
    FROM student_performance
    GROUP BY department
"""

panel2 = pd.read_sql_query(query2, conn)

display(panel2)

query3 = """
    SELECT name,
           total_score
    FROM student_performance
    ORDER BY total_score DESC
    LIMIT 8
"""

panel3 = pd.read_sql_query(query3, conn)

display(panel3)

query4 = """
    SELECT gender,
           ROUND(AVG(attendance_percentage),2)
           AS avg_attendance
    FROM student_performance
    GROUP BY gender
"""

panel4 = pd.read_sql_query(query4, conn)

display(panel4)

import pandas as pd
import sqlite3

# Read CSV file
df = pd.read_csv("student_performance.csv")

# Create total_score column
df['total_score'] = (
    df['math_score'] +
    df['programming_score']
)

# Create database connection
conn = sqlite3.connect("student_performance.db")

# Store dataframe into SQL table
df.to_sql(
    'student_performance',
    conn,
    if_exists='replace',
    index=False
)

print("Table created successfully")

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt


conn = sqlite3.connect("student_performance.db")

query1 = """
    SELECT department,
           ROUND(AVG(math_score),2) AS avg_math
    FROM student_performance
    GROUP BY department
    ORDER BY avg_math DESC
"""

panel1 = pd.read_sql_query(query1, conn)

query2 = """
    SELECT department,
           COUNT(*) AS total_students
    FROM student_performance
    GROUP BY department
"""

panel2 = pd.read_sql_query(query2, conn)

query3 = """
    SELECT name,
           total_score
    FROM student_performance
    ORDER BY total_score DESC
    LIMIT 8
"""

panel3 = pd.read_sql_query(query3, conn)

query4 = """
    SELECT gender,
           ROUND(AVG(attendance_percentage),2)
           AS avg_attendance
    FROM student_performance
    GROUP BY gender
"""

panel4 = pd.read_sql_query(query4, conn)

fig, axes = plt.subplots(2, 2, figsize=(16,10))

fig.suptitle(
    "Student Performance Dashboard",
    fontsize=20,
    fontweight='bold'
)

axes[0,0].bar(
    panel1['department'],
    panel1['avg_math'],
    color=['skyblue','orange','green','purple']
)

axes[0,0].set_title("Avg Math Score by Department")
axes[0,0].set_ylabel("Average Score")
axes[0,0].grid(alpha=0.3)

axes[0,1].pie(
    panel2['total_students'],
    labels=panel2['department'],
    autopct='%1.0f%%',
    startangle=90
)

axes[0,1].set_title("Students per Department")

axes[1,0].barh(
    panel3['name'],
    panel3['total_score'],
    color='skyblue'
)

axes[1,0].set_title("Top 8 Students")
axes[1,0].set_xlabel("Total Score")

axes[1,0].invert_yaxis()

axes[1,1].bar(
    panel4['gender'],
    panel4['avg_attendance'],
    color=['skyblue','orange']
)

axes[1,1].set_title("Gender Avg Attendance")
axes[1,1].set_ylabel("Attendance %")

plt.tight_layout()

plt.show()

conn.close()