# -*- coding: utf-8 -*-
"""DAY2-class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrvKxze6icfI3e09kE687m42J0eDpMCc
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
#traceback ha full la show panna ma....just simple ha show pannaum
warnings.filterwarnings('ignore')

print("All libraries imported successfully")
print(f"panda version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.version}")

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('student_performance.csv')

print(f"Dataset loaded: {df.shape[0]}students,{df.shape[1]} columns")
print(f"columns:{df.columns.tolist()}")
print(f"rows: {df.index.tolist()}")
df.head(6)

"""sqlite3.connect()  - create or open the db files (if exsisting it will use it self) ||
conn - is the connection object( code to db) ||
cursor - tool that executes the sql commands ||
df.to_sql() - write dataframes as the database table
"""

import sqlite3
import pandas as pd
import os

# Step 1: Close old connections safely
try:
    conn.close()
except:
    pass

# Step 2: Delete old database file if exists
if os.path.exists("college.db"):
    os.remove("college.db")

# Step 3: Create fresh database connection
conn = sqlite3.connect("college.db")

# Step 4: Store dataframe into database
df.to_sql(
    "students",
    conn,
    if_exists="replace",
    index=False
)

# Step 5: Verify rows
cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM students")

count = cursor.fetchone()[0]

print("Database created successfully")
print(f"Students table has {count} rows")

# Step 6: Close connection
conn.close()

conn = sqlite3.connect('college.db')
cursor = conn.cursor()
df.to_sql(
    'students',
    conn,  #database connection
    if_exists='replace',  #if exists it will replace
    index=False    #do not write dataframe row numbers as a column and it will be start with the 1
)
cursor.execute("SELECT COUNT(*) FROM students")  #cursor-tool to execute the sql and students - table
count=cursor.fetchone()[0]
print(f"Database 'college.db' created successfully")
print(f"Table 'students' has {count} rows")
conn.close()

import sqlite3

# Reconnect to database
conn = sqlite3.connect("college.db")

# Create cursor
cursor = conn.cursor()


#PRAGMA is a special SQLite command
cursor.execute("PRAGMA table_info(students)")
columns_info=cursor.fetchall()

print(f"{'Column Name':<25}{'Data Type':<12}")
print("-"*38)
for col in columns_info:
  print(f"{col[1]:<25}{col[2]:<12}")

"""SELECT column1, column ------which columns to show   ||
FROM   table_name    -------which table to read from  ||
WHERE condition  -----------filter rows ||
GROUP BY column--------group rows ||
HAVING group_condition ------filter groups ||
ORDER BY column DESC ------sort result ||
LIMIT 10; -------max rows to return ||
"""

import pandas as pd
import sqlite3

# Read CSV file
df = pd.read_csv("student_performance.csv")

# Create database connection
conn = sqlite3.connect("student.db")

# Store CSV data into SQL table
df.to_sql("student_performance", conn, if_exists="replace", index=False)

# SQL Query
query = """
SELECT *
FROM student_performance
ORDER BY rowid DESC
LIMIT 5;
"""

# Execute query
result = pd.read_sql_query(query, conn)

# Display output
display(result)

query = """
SELECT *
FROM student_performance
ORDER BY rowid DESC
LIMIT 14 OFFSET 12;
"""

result = pd.read_sql_query(query, conn)

display(result)

query2 = """
    SELECT name, department, math_score
    FROM student_performance
    ORDER BY math_score DESC
    LIMIT 10
"""

result = run_query(query2, "Top 10 Students by Math Score")

display(result)

query3="""
    SELECT *
    FROM student_performance
    WHERE programming_score BETWEEN 50 AND 75
"""
result=run_query(query3,"Students with Programming Score between 50 and 75")
display(result)

query4="""
    SELECT name, math_score, science_score, programming_score, attendance_percentage
    FROM student_performance
    WHERE department='Computer Science'
    ORDER BY programming_score DESC
    LIMIT 5
"""
result = run_query(query4, "Top 5 Students in Computer Science")

display(result)

"""Distinct======for unique department only

"""

query5 = """
    SELECT DISTINCT department
    FROM student_performance
"""

result = run_query(query5, "Top 5 Students in Computer Science")

display(result)

query6 = """
    SELECT department,
           MAX(programming_score) AS highest_score,
           MIN(programming_score) AS lowest_score
    FROM student_performance
    WHERE department IN ('Computer Science', 'Electronics', 'Mechanical')
    GROUP BY department
"""

result = run_query(
    query6,
    "Highest and Lowest Programming Scores in Three Departments"
)

display(result)

query7 = """
SELECT department, COUNT(*) AS total_students
FROM student_performance
GROUP BY department
ORDER BY total_students DESC
LIMIT 1;
"""

result = run_query(query7)

display(result)

query8="""
    SELECT name, department, attendance_percentage
    FROM student_performance
    WHERE attendance_percentage >90
    AND department !='Civil'
    ORDER BY attendance_percentage DESC
"""
result = run_query(query8, "Excluded the one department")
display(result)

query9="""
    SELECT name, department, attendance_percentage
    FROM student_performance
    WHERE attendance_percentage >80
    AND attendance_percentage!=79
    ORDER BY attendance_percentage DESC
"""
result = run_query(query9, "Excluded the one department")
display(result)

import pandas as pd

dept_data= {
    'dept_code' : ['CS','EC','ME','CE'],
    'dept_name': ['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name' :['Dr.Sharma','Dr.Reddy','Dr.Patel','Dr.Kumar'],
    'established':[1985,1988,1972,1965],
    'intake' : [60,60,60,60]
}
dept_df = pd.DataFrame(dept_data)
dept_df

import sqlite3

# Create database connection
conn = sqlite3.connect("student.db")

# Store departments table
dept_df.to_sql(
    'departments',
    conn,
    if_exists='replace',
    index=False
)

print("Created 'departments' table:")
print(dept_df.to_string(index=False))

dept_df.to_sql('departments', conn, if_exists='replace', index=False)

print("Created 'departments' table:")
print(dept_df.to_string(index=False))

dept_map = {
    'Computer Science':'CS',
    'Electronics':'EC',
    'Mechanical':'ME',
    'Civil':'CE'
}

df['dept_code'] = df['department'].map(dept_map)
df.to_sql('students', conn, if_exists='replace', index=False)

print("\nUpdated Students table with dept_code column")

from google.colab import files
uploaded = files.upload()

import pandas as pd
import sqlite3

# Read CSV file
df = pd.read_csv("student_performance.csv")

# Database connection
conn = sqlite3.connect("student.db")

# Department data
dept_data = {
    'dept_code': ['CS','EC','ME','CE'],
    'dept_name': ['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name': ['Dr.Sharma','Dr.Reddy','Dr.Patel','Dr.Kumar'],
    'established': [1985,1988,1972,1965],
    'intake': [60,60,60,60]
}

# Create dataframe
dept_df = pd.DataFrame(dept_data)

# Store department table
dept_df.to_sql(
    'departments',
    conn,
    if_exists='replace',
    index=False
)

print("Created 'departments' table:")
print(dept_df.to_string(index=False))

# Mapping
dept_map = {
    'Computer Science':'CS',
    'Electronics':'EC',
    'Mechanical':'ME',
    'Civil':'CE'
}

# Add dept_code column
df['dept_code'] = df['department'].map(dept_map)

# Store updated students table
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

print("\nUpdated Students table with dept_code column")

display(df.head())

def run_query(sql, description=""):

    if description:
        print("\n" + "=" * 55)
        print(description)
        print("=" * 55)

    result = pd.read_sql_query(sql, conn)

    return result

query_join = """
    SELECT
        s.name,
        s.math_score,
        d.dept_name,
        d.hod_name,
        d.established
    FROM students AS s
    INNER JOIN departments AS d
        ON s.dept_code = d.dept_code
    ORDER BY s.math_score DESC
    LIMIT 5
"""

result = run_query(query_join, "Top 5 Students with Department Details")
display(result)

flg, ax=plt.subplots(figsize=(width,height))  #create canvas
ax.bar(x,y)                                   #Drwa the chart
ax.set_xlable('...')                          #Add title
ax.set_ylable('...')                          #Label x-axis
ax.set_title('...')                           #lable y-axis
plt.tight_layout()                            #fix label clipping
plt.show()                                    #display chart

import matplotlib.pyplot as plt

chart1_sql = """
    SELECT department,
           ROUND(AVG(math_score),2) AS avg_math
    FROM students
    GROUP BY department
    ORDER BY avg_math DESC
"""

chart1_data = pd.read_sql_query(chart1_sql, conn)

fig, ax = plt.subplots(figsize=(10,6))

# Bar graph with color
ax.bar(
    chart1_data['department'],
    chart1_data['avg_math'],
    color='pink'
)

ax.set_xlabel('Department')
ax.set_ylabel('Average Math Score')
ax.set_title('Average Math Score by Department')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data
departments = ['CS', 'EC', 'ME', 'CE']
avg_marks = [92, 85, 78, 88]

# 1. Create figure
plt.figure(figsize=(10,6))

# 2. Create bar graph
plt.bar(
    departments,
    avg_marks,
    color=['skyblue', 'orange', 'green', 'purple'],
    linewidth=2
)

# 3. X-axis label
plt.xlabel("Departments", fontsize=14)

# 4. Y-axis label
plt.ylabel("Average Marks", fontsize=14)

# 5. Title
plt.title("Average Math Score by Department", fontsize=18)

# 6. Grid
plt.grid()

# 7. X-axis ticks rotation
plt.xticks(rotation=15)

# 8. Y-axis ticks
plt.yticks([0,20,40,60,80,100])

# 9. Legend
plt.legend(['Department Scores'])

# 10. Tight layout
plt.tight_layout()

# 11. Show graph
plt.show()