# -*- coding: utf-8 -*-
"""DAY2-practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtcaD5HfuuEK89G4NDqx3pfGl1UTYEJm
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("student_performance.csv")

import sqlite3

conn = sqlite3.connect("student.db")

df.to_sql(
    'student_performance',
    conn,
    if_exists='replace',
    index=False
)

query1 = """
    SELECT ROUND(AVG(programming_score),2)
           AS avg_programming_score
    FROM student_performance
    WHERE gender = 'Female'
"""

result1 = pd.read_sql_query(query1, conn)

display(result1)

query2_where = """
    SELECT name, math_score
    FROM student_performance
    WHERE math_score > 80
"""

result2_where = pd.read_sql_query(query2_where, conn)

display(result2_where)

query2_having = """
    SELECT department,
           AVG(math_score) AS avg_math
    FROM student_performance
    GROUP BY department
    HAVING AVG(math_score) > 85
"""

result2_having = pd.read_sql_query(query2_having, conn)

display(result2_having)

query3 = """
    SELECT department,
           ROUND(AVG(attendance_percentage),2)
           AS avg_attendance
    FROM student_performance
    GROUP BY department
    HAVING AVG(attendance_percentage) > 85
"""

result3 = pd.read_sql_query(query3, conn)

display(result3)

query = """
    SELECT *
    FROM student_performance
"""

result = pd.read_sql_query(query, conn)

display(result)

query5 = """
    SELECT department,
           ROUND(AVG(programming_score),2)
           AS avg_programming
    FROM student_performance
    GROUP BY department
    ORDER BY avg_programming DESC
"""

result5 = pd.read_sql_query(query5, conn)

display(result5)

from google.colab import files
uploaded = files.upload()

import pandas as pd
import sqlite3

# Read CSV file
df = pd.read_csv("student_performance.csv")

# Database connection
conn = sqlite3.connect("student.db")

# Department data
dept_data = {
    'dept_code': ['CS','EC','ME','CE'],
    'dept_name': ['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name': ['Dr.Sharma','Dr.Reddy','Dr.Patel','Dr.Kumar'],
    'established': [1985,1988,1972,1965],
    'intake': [60,60,60,60]
}

# Create dataframe
dept_df = pd.DataFrame(dept_data)

# Store department table
dept_df.to_sql(
    'departments',
    conn,
    if_exists='replace',
    index=False
)

print("Created 'departments' table:")
print(dept_df.to_string(index=False))

# Mapping
dept_map = {
    'Computer Science':'CS',
    'Electronics':'EC',
    'Mechanical':'ME',
    'Civil':'CE'
}

# Add dept_code column
df['dept_code'] = df['department'].map(dept_map)

# Store updated students table
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

print("\nUpdated Students table with dept_code column")

display(df.head())

def run_query(sql, description=""):

    if description:
        print("\n" + "=" * 55)
        print(description)
        print("=" * 55)

    result = pd.read_sql_query(sql, conn)

    return result

dept_map = {
    'Computer Science': 'CS',
    'Electronics': 'EC',
    'Mechanical': 'ME',
    'Civil': 'CE'
}

df['dept_code'] = df['department'].map(dept_map)

df.to_sql(
    'student_performance',
    conn,
    if_exists='replace',
    index=False
)

# LEFT JOIN

query_left = """
    SELECT
        s.name,
        s.math_score,
        d.dept_name,
        d.hod_name,
        d.established
    FROM student_performance AS s
    LEFT JOIN departments AS d
        ON s.dept_code = d.dept_code
    ORDER BY s.math_score DESC
    LIMIT 5
"""

result_left = pd.read_sql_query(query_left, conn)

display(result_left)

# RIGHT JOIN (Simulated in SQLite)

query_right = """
    SELECT
        s.name,
        s.math_score,
        d.dept_name,
        d.hod_name,
        d.established
    FROM departments AS d
    LEFT JOIN student_performance AS s
        ON s.dept_code = d.dept_code
    ORDER BY s.math_score DESC
    LIMIT 5
"""

result_right = pd.read_sql_query(query_right, conn)

display(result_right)

# FULL JOIN (Simulated in SQLite)

query_full = """
    SELECT
        s.name,
        s.math_score,
        d.dept_name,
        d.hod_name,
        d.established
    FROM student_performance AS s
    LEFT JOIN departments AS d
        ON s.dept_code = d.dept_code

    UNION

    SELECT
        s.name,
        s.math_score,
        d.dept_name,
        d.hod_name,
        d.established
    FROM departments AS d
    LEFT JOIN student_performance AS s
        ON s.dept_code = d.dept_code

    ORDER BY math_score DESC
    LIMIT 5
"""

result_full = pd.read_sql_query(query_full, conn)

display(result_full)