# -*- coding: utf-8 -*-
"""DAY7:EmbeddingsHug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Q6YcIVNurvhg94fWIr6UDGzJd1cXa-3
"""

!pip install chromadb sentence-transformers -q
print("Installation complete!")

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
import chromadb

print("All libraries imported successfully ")
print(f"ChromaDB version {chromadb.__version__}")

#key word searching
documents = {
    "ETL is used to clean and transform data ",
    "A vehicle is a mode of transportation",
    "Cars and trucks are popular automobiles",
    "SQL is used to query database",
    "Machine learning rains models on data"
}
search_word="Vehicle"
print("=" *60)
print(f"Search word: {search_word}")
print("=" *60)

for i, doc in enumerate(documents):
  if search_word.lower() in doc.lower():
    print(f"FOUND[doc_{i}]: {doc}")
  else:
    print(f"MISSED [doc_{i}: {doc}")

print()
print("PROBLEM: doc_2 talks about 'Cars and trucks' - which ARE vehicles")
print("But keyword search MISSED it beacus it searched for the exact word 'vehicle' ")

#Load the Embedding Model
#ensures that how the backend is working

print("Loading embedding model")
model=SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully")

#first single  embedding content
sentence ="ETL is used to clean and transform data"
embedding=model.encode(sentence)

print(f"Input sentence: '{sentence}'")
print()
print(f"Embedding type: {type(embedding)}")
print(f"Embedding shape: {embedding.shape}")
print(f"First 10 number: {embedding[:10].round(4)}")    #cosine similarity
print(f"Min Value: {embedding.min():.4f}")
print(f"Max Value: {embedding.max():.4f}")

sentences = [
    "ETL is used to clean data.",
    "Machine learning models require quality datasets.",
    "Data Science helps in decision making.",
    "Semantic search uses embeddings.",
    "Python is widely used in AI applications."
]

for sentence in sentences:

    embedding1 = model.encode(sentence)

    print("Input:", sentence)
    print()

    print("Embedding type:", type(embedding1))
    print("Embedding shape:", embedding1.shape)
    print("First 10 numbers:", embedding1[:10].round(4))
    print("Min value:", embedding1.min().round(4))
    print("Max value:", embedding1.max().round(4))

import numpy as np
def cosine_similarity(vec_a,vec_b):
  """Calculate cosine similarity between two vectors"""
  dot_product=np.dot(vec_a,vec_b)
  norm_a=np.linalg.norm(vec_a)
  norm_b=np.linalg.norm(vec_b)
  return dot_product/(norm_a*norm_b)
sim_01=cosine_similarity(embeddings[0],embeddings[1])
sim_02=cosine_similarity(embeddings[0],embeddings[2])
sim_12=cosine_similarity(embeddings[1],embeddings[2])
print(sim_01)
print(sim_02)
print(sim_12)

