# -*- coding: utf-8 -*-
"""DAY7:Fiass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oIgtlUNEycu7SDoU7v0Wmwljx4rpbP_V
"""

!pip install langchain langchain-community langchain-groq faiss-cpu sentence-transformers -q
!pip install pypdf -q

#installl fpdf
!pip install fpdf --q

from fpdf import FPDF
import os

pdf=FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)

content=[
    "Develop training programs offering globally recognized certifications in AI and Robotics, covering areas such as machine learning, computer vision, and robotics engineering.",
"Provide practical projects and organize hackathon to furnish students with real-world experience in developing AI-driven solutions and designing robotic systems.",
"Support research initiatives and creative endeavors to drive innovation and contribute to the advancement of AI and robotics technologies enhancing human-robot interaction.",
"Offer consultancy services to industry partners seeking specialized guidance in AI and robotics, delivering tailored solutions and strategic recommendations.",
"Provide guidance for students aspiring to build careers in AI and robotics, internships, and industry collaborations to nurture their professional development."
]
for line in content:
  pdf.multi_cell(0,10,line)

os.makedirs("data", exist_ok=True)
pdf_file ="data/ragg.pdf"

pdf.output(pdf_file)
print(f"PDF saved as {pdf_file}")
print(f"Files in current directory: {os.listdir('.')}")

import os
from langchain_community.document_loaders import PyPDFLoader #to load the pdf content
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

os.environ["GROQ_API_KEY"]=""

loader = PyPDFLoader("data/ragg.pdf")
pages=loader.load()

splitter =CharacterTextSplitter(chunk_size=500, chunk_overlap=50)
documents=splitter.split_documents(pages)

embedding=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
db=FAISS.from_documents(documents, embedding)

llm=ChatGroq(model="llama-3.1-8b-instant")

prompt=PromptTemplate.from_template(
    "Use the following context to answer the question:\n\nContext:\n{context}\n\nQuestion:\n{question}\nAnswer:"
)
parser=StrOutputParser()

def ask_pdf(query: str):
  docs=db.similarity_search_with_score(query, k=3)
  context="\n\n".join([d[0].page_content for d in docs])
  chain = prompt |llm | parser
  return chain.invoke({"context" : context,"question":query})

while True:
  query = input ("\nAsk a question (or type 'exit')")
  if query.lower() == "exit":
    break
  answer=ask_pdf(query)
  print(answer)

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]=""

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

prompt=PromptTemplate(
    input_variables=["instruction"],
    template="generate a streamlite code and the installations step by step to run in the google colab and save it \n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain = prompt | llm | parser

response=chain.invoke({
    "instruction" : "Give the calculator code"})
print(response)

!pip install streamlit

import streamlit as st

import streamlit as st
from streamlit import caching

# Create a title for the calculator
st.title("Simple Calculator")

# Create input fields for the two numbers
num1 = st.number_input("Enter the first number:")
num2 = st.number_input("Enter the second number:")

# Create a dropdown menu for the operation
operation = st.selectbox("Select the operation:", ["Addition", "Subtraction", "Multiplication", "Division"])

# Perform the operation based on the user's selection
if operation == "Addition":
    result = num1 + num2
elif operation == "Subtraction":
    result = num1 - num2
elif operation == "Multiplication":
    result = num1 * num2
elif operation == "Division":
    if num2 != 0:
        result = num1 / num2
    else:
        result = "Error: Division by zero is not allowed"

# Display the result
st.write("Result:", result)

caching.clear_cache()
st.experimental_rerun()