# -*- coding: utf-8 -*-
"""DAY7-llamaindex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJSl9X8G1uj_IgAUqf9dYQw4BEKGra9R
"""

!pip install llama-index llama-index-llms-groq sentence-transformers --q

!pip install llama-index-embeddings-huggingface --q

import os  #for the creation of the new folder and the new file
from textwrap import dedent #anyfile to the text file

os.makedirs("data",exist_ok =True)
file_path="data/sece.txt"
content=dedent("""
Bridging Minds and Machines with AI and Robotics

Artificial Intelligence and Robotics are at the forefront of technological advancement, revolutionizing industries and reshaping the way we live and work. From autonomous vehicles to smart assistants, these fields drive innovation, efficiency, and progress, empowering humanity with intelligent machines that augment our capabilities and improve our quality of life.
ABOUT CoE

Welcome to the Centre for Artificial Intelligence and Robotics, where imagination meets innovation. Our collaborative hub pioneers cutting-edge research, education, and industry partnerships to push the boundaries of AI and Robotics. Through interdisciplinary collaboration, state-of-the-art facilities, and experiential learning, we’re shaping the future of intelligent systems and empowering the next generation of AI and robotics leaders. Join us as we build a future where humans and machines work together to solve the world’s most pressing challenges.
OBJECTIVES

Develop training programs offering globally recognized certifications in AI and Robotics, covering areas such as machine learning, computer vision, and robotics engineering.

Provide practical projects and organize hackathon to furnish students with real-world experience in developing AI-driven solutions and designing robotic systems.

Support research initiatives and creative endeavors to drive innovation and contribute to the advancement of AI and robotics technologies enhancing human-robot interaction.

Offer consultancy services to industry partners seeking specialized guidance in AI and robotics, delivering tailored solutions and strategic recommendations.

Provide guidance for students aspiring to build careers in AI and robotics, internships, and industry collaborations to nurture their professional development.

CENTRE HEAD

Dr.Thenmozhi M, Assistant Professor / AIDS
CENTRE COORDINATORS

Ms.S.Sindhuja, Assistant Professor / AIML
EVENTS

S.No	Name of the Event	Resource Person
Date
1	Mastering in MLO ps	Mr. C.B. Veerakumar, Associate Engineering Analyst, Wipro Technologies	02.07.25–18.07.25
2	Introduction to Data Bricks	Ms. K. Parvathy, AP/AI&DS	03.05.25
3	Fundamentals of Generative AI	Ms. K. Parvathy, AP/AI&DS	29.04.25
4	Hand-on Session on Exploratory Data Analysis	Ms. K. Parvathy, AP/AI&DS	05.04.25
5	Basics of Business Intelligence	Ms. K. Parvathy, AP/AI&DS	05.04.25
6	Data Visualization Tools and Techniques	Ms. K. Parvathy, AP/AI&DS	15.03.25
7	Hands-on Session on Power BI	Ms. K. Parvathy, AP/AI&DS	15.02.25
8	Hands on in RoboDk	Dr.M.Thenmozhi, AP/AI&DS	30.11.2024
9	(AN) ROS - Beginners and Intermediate Course	Mr.K.Deiva Praksh, Robotics Software Developer, GOAT Robotics, Coimbatore	23.11.2024
10	(FN) Hands on in RoboDk	Mr. M.Saravana Kumar, Ms.A.Sandiya, III AIDS B	23.11.2024
11	AI Algorithm needed for Robotics	Mr.P.T.Balasurya and G. Asmita, III AI&DS	09.11.2024
12	Gazeobo Simulation model and Jarvis Kit - Demonstration	Mr.P.T.Balasurya and Mr.N.Gokulan, III AI&DS Students	26.10.2024
13	Exploring Simulation - Robotics	Dr.M.Thenmozhi, AP/AI&DS, Ms.S.Sindhuja, AP/CSE(AIML), SECE	19.10.2024
14	(AN) Robot Operating System - Basic and Medium Course	Mr.K.Deiva Praksh, Robotics Software Developer, GOAT Robotics, Coimbatore	05.10.2024
15	(FN) Introduction to AI & Robotics: Components and Applications	Dr.M.Thenmozhi, AP/AI&DS, Ms.S.Sindhuja, AP/CSE(AIML), SECE	05.10.2024
16	AI & Robotics Innovation: Engineering the Future of Automation	Mr.Balaji Narayanan, Sr. Robotics Software Developer, Intrino Robotics & Technologies Pvt. Ltd., Chennai	14.09.2024
17	AI Robotics: Bridging intelligence and Automation	Mr.S.Sridhar, CEO & Founder, Intrino Robotics & Technologies Pvt. Ltd., Chennai	31.08.2024
18	Artificial Intelligence and Robotics	Mr.G.Rajesh Mani Kumar, Solution Engineer, Proximus, Brussels, Belgium	24.08.2024
19	Transforming Tomorrow: The Age of AI & Robotics	Mr.S.Sridhar, CEO & Founder, Intrino Technologies Pvt Ltd	29.07.2024 to 14.08.2024
20	Robots in Action: AI and Robotics in Practice	Dr.S.Ganeshkumar, ASP/Mech, Dr.M.Thenmozhi, AP/AIDS	25.05.2024
21	Designing the Future: AI and Robotics in Engineering and Design	Dr.S.Ganeshkumar, ASP/Mech, Dr.M.Thenmozhi, AP/AIDS	27.04.2024
22	Artificial Minds, Mechanical Bodies: Exploring AI and Robotics	Dr.M.Thenmozhi, AP/AIDS	23.03.2024
23	The Robotics Revolution: How AI is Shaping Tomorrow's Technology	Dr.Uma maheswari Sharma, Assistant Professor, Department of CSE, NIT Calicut	09.03.2024
24	Merging Minds and Machines: The Convergence of AI and Robotics	Dr.S.Ganeshkumar, ASP/Mech	24.02.2024
CoE OFFICE

Centre of Excellence – Artificial Intelligence and Robotics
Sri Eshwar College of Engineering
Kondampatti [Post], Vadasithur (via), Coimbatore – 641 202,
Tamil Nadu, India
Email: coe-robotics@sece.ac.in

""").strip()

with open(file_path,"w", encoding="utf-8") as f:
  f.write(content)


print(f"Created file: {file_path} (len{content.splitlines()} lines)")
print("Successfully loaded")

#external kuda connect panni nambala work pann mudiyum
import os
from llama_index.llms.groq import Groq
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

os.environ['GROQ_API_KEY']=""

llm=Groq(model="llama-3.1-8b-instant")
#importing multimodel
embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

#Embedding modal (local huggingface) changes to the vectors
file_path="data/sece.txt"
documents=SimpleDirectoryReader(input_files=[file_path]).load_data()

#load to the text document
index=VectorStoreIndex.from_documents(documents,llm=llm,embed_model=embed_model)

#create index la vectors ha store pandrom (document apro model ha load pandrom )
query_engine = index.as_query_engine(llm=llm)

#query engine
response=query_engine.query("Who is the mlops trainer?")

#ask question
print(response)

#external kuda connect panni nambala work pann mudiyum
import os
from llama_index.llms.groq import Groq
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

os.environ['GROQ_API_KEY']=""

llm=Groq(model="llama-3.1-8b-instant")
#importing multimodel
embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

#Embedding modal (local huggingface) changes to the vectors
file_path="data/Moulika_Resume.txt"
documents=SimpleDirectoryReader(input_files=[file_path]).load_data()

#load to the text document
index=VectorStoreIndex.from_documents(documents,llm=llm,embed_model=embed_model)

#create index la vectors ha store pandrom (document apro model ha load pandrom )
query_engine = index.as_query_engine(llm=llm)

#query engine
response=query_engine.query("what are the skills does moulika have?")

#ask question
print(response)

#external kuda connect panni nambala work pann mudiyum
import os
from llama_index.llms.groq import Groq
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

os.environ['GROQ_API_KEY']=""

llm=Groq(model="llama-3.1-8b-instant")
#importing multimodel
embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L6-v2")

#Embedding modal (local huggingface) changes to the vectors
file_path="data/"

#load to the text document
index=VectorStoreIndex.from_documents(documents,llm=llm,embed_model=embed_model)

#create index la vectors ha store pandrom (document apro model ha load pandrom )
query_engine = index.as_query_engine(llm=llm)

#query engine
response=query_engine.query("what is the candidate name?")

#ask question
print(response)

